#-----------------------------------------------------------------
#==================================================================#
#                                                                  #
#               TotemsPlus by FlailoftheLord.                      #
#          -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-                 #
#   ______               __        _____                           #
#   |       |           /  \         |        |                    #
#   |__     |          /____\        |        |                    #
#   |       |         /      \       |        |                    #
#   |       |_____   /        \    __|__      |______              #
#                                                                  #
#==================================================================#
#-----------------------------------------------------------------
# Plugin Prefix for chat Messages
# there is no need for a space after the prefix
# the plugin automatically puts a space between the prefix and the text! ;)
Prefix: "&8(&2&lT&6&l+&8)"

ReloadMessage: "&aconfig reloaded!"

NoPermissionMessage: "&cyou do not have permission to use this command"

ResurrectMessage: "&aYou died, but had a totem in your inventory and were resurrected!"

TotemGiveSelfMessage: "&eYou gave yourself a totem!"

TotemReceivedMessage: "&eYou were given a totem!"

TotemGivenMessage: "&eYou gave %player% a totem!"

## Whether to show the effect on the players screen when they die.
ShowTotemEffect: true

TotemEffects:
- "SLOW_FALLING"
- "REGENERATION"
- "DAMAGE_RESISTANCE"
- "ABSORBTION"

## The duration of the Applied potion effects in seconds
# The Absorption effect lasts 30 seconds longer.
PotionEffectDuration: 20

# The power of the Potion effects applied.
PotionEffectStrength: 3

# Hide the potion effect particles?
HideEffectParticles: false

# How long between each use of a totem? (in seconds)
Cooldown: 60

# Whether cooldowns should be applied to vanilla totems (totems in hand when dying)
CooldownOnVanillaBehavior: true

# Ignore damage from void/other plugins?
IgnoreVoidDamage: true

# Message to send to the player when totems are on cooldown.
TotemOnCooldown: "&cTotems have been put on cooldown for {0} seconds!"
