main: me.flail.totemsplus.TotemsPlus
name: TotemsPlus
version: 1.3
api-version: 1.13
author: FlailoftheLord
website: flailofthelord.com
description: Better Totems of Undying!

commands:
    totemsplus:
      usage: '/totemsplus [reload]'
      description: 'main command for the totems plugin'
      permission: totemsplus.command
      aliases: [totems, totem, tplus, totemplus]

permissions:
    totemsplus.use:
      default: true
      description: use totems on death which aren't in your hand!
      
    totemsplus.command.give:
      default: op
    totemsplus.command.get:
      default: op
    totemsplus.command.reload:
      default: op
    totemsplus.bypasscooldown:
      default: op

    totemsplus.command:
      description: ability to use /totemsplus and any aliases
      default: op
      children:
        totemsplus.command.give: true
        totemsplus.command.reload: true
        totemsplus.command.get: true
        totemsplus.use: true
      

  